name: Run Postman Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman and HTML Reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run API_Booking.postman_collection.json \
            --environment environment-dev.json
            --iteration-data dados_projeto_booking.csv
            --reporters cli,junit \
            --reporter-junit-export results.xml


            - name: Upload Detailed HTML Report
              uses: actions/upload-artifact@v4
              with:
              name: postman-detailed-html-report
              path: ./results/report.html
